Header Layout and Styling
accessiblecommunity/accessiblecommunity.github.io pull request #24
Opened 2023-11-09 21:16 UTC by alexisreytech

Add header layout with dropdown styling. Some global styling changes can further improve this once merged with main. One issue is that the menu toggle seems to expand automatically, without responding properly to user input.

This addresses #2

2023-11-10 19:53 UTC, brian-montgomery requested changes
Alexis, I think this is a great start. 

A couple of small things:
1. Set the "Accessible Community" in our brand color (`text-ac`).
2. Remove the "Jump to Footer" skip link. Going to the main content is good enough.
3. Move the collapse to the left side, since all of the header collapse menu is on the left side.
4. Remove the search form, and replace it with a donate link.
5. Remove the last HR.

2023-11-11 02:23 UTC, alexisreytech commented
@brian-montgomery, the requested changes have been addressed. I also made changes to create focus indicators for the menu, and improve the contrast of the dropdowns.

2023-11-12 19:28 UTC, brian-montgomery approved these changes

2023-11-12 19:29 UTC, merged

2023-11-12 19:36 UTC, brian-montgomery commented
It looks great, Alexis. I've merged your changes in.